<?php
/**
 * 
 *
 */
 ?>
<div class="container">
	<form action=""  class="form-inline" method="post" enctype="application/x-www-form-urlencoded" id="form_login">
		<input type="text" class="text" value="" id="username" name="username" placeholder="Email">
		<input type="password" class="text" value="" id="password" name="password" placeholder="Mot de passe">&nbsp;&nbsp;
		<input type="submit" value="Connexion" id="submit" name="submit" class="btn">
	</form>
</div>